# Base image for ROS Humble on Ubuntu Jammy
FROM ros:humble-ros-core-jammy

# Install necessary tools and ROS packages
RUN apt-get update && apt-get install --no-install-recommends -y \
    build-essential \
    git \
    python3-colcon-common-extensions \
    python3-rosdep \
    python3-vcstool \
    ros-humble-ros-base=0.10.0-1* \
    ros-humble-rviz2 \
    ros-humble-cv-bridge \
    python3-opencv \
    ros-humble-vision-msgs \
    libboost-dev \
    ros-humble-xacro \
    ros-humble-depth-image-proc \
    ros-humble-camera-info-manager \
    ros-humble-camera-calibration \
    ros-humble-image-transport-plugins \
    ros-humble-image-pipeline \
    ros-humble-diagnostic-updater \
    wget \
    cmake \
    && rm -rf /var/lib/apt/lists/*

# Download and install DepthAI core using wget
RUN wget https://github.com/luxonis/depthai-core/releases/download/v2.27.0/depthai-core-v2.27.0.tar.gz && \
    tar -xzf depthai-core-v2.27.0.tar.gz -C /opt && \
    rm depthai-core-v2.27.0.tar.gz

# Set the environment variables for DepthAI
ENV CMAKE_PREFIX_PATH=/opt/depthai-core-v2.27.0:$CMAKE_PREFIX_PATH
ENV depthai_DIR=/opt/depthai-core-v2.27.0/lib/cmake/depthai

# Initialize rosdep
RUN rosdep init && rosdep update --rosdistro $ROS_DISTRO

# Clone depthai-ros repository
WORKDIR /root/ros2_ws/src
RUN git clone https://github.com/luxonis/depthai-ros.git

# Remove unnecessary packages from the depthai-ros repository
RUN rm -rf /root/ros2_ws/src/depthai-ros/depthai_bridge \
           /root/ros2_ws/src/depthai-ros/depthai_filters \
           /root/ros2_ws/src/depthai-ros/depthai_descriptions

# Build the workspace using colcon
WORKDIR /root/ros2_ws
RUN bash -c ". /opt/ros/humble/setup.sh && colcon build --packages-select depthai_ros_msgs"

# Source the workspace setup script
RUN echo "source /root/ros2_ws/install/setup.bash" >> /root/.bashrc

# Install rosbridge_suite in a separate step
RUN apt-get update && apt-get install -y \
    ros-humble-rosbridge-suite

# Set the default command to launch rosbridge_server
CMD ["ros2", "launch", "rosbridge_server", "rosbridge_websocket_launch.xml"]
